package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/emailquangto/redmine4go"
	"github.com/joho/godotenv"
)

func main() {
	godotenv.Load("../.env")

	baseURL := os.Getenv("BASE_URL")
	apiKey := os.Getenv("API_KEY")
	apiFormat := os.Getenv("API_FORMAT")
	projectId := os.Getenv("PROJECT_ID")
	projectName := os.Getenv("PROJECT_NAME")

	c := redmine4go.CreateClient(baseURL, apiKey, apiFormat)

	// get list of projects
	include := "" // trackers, issue_categories, enabled_modules
	projectList, error := c.GetProjects(include)
	if error == nil {
		fmt.Printf("%s\n", "=====get list of projects=====")
		fmt.Printf("Number of projects = %d\n", projectList.TotalCount)
		if projectList.TotalCount > 0 {
			fmt.Printf("project 1 - Name = %s\n", projectList.Projects[0].Name)
			fmt.Printf("project 1 - ID = %d\n", projectList.Projects[0].ID)
			fmt.Printf("project 1 - Status = %d\n", projectList.Projects[0].Status)
		}
	} else {
		fmt.Printf("%s\n", error)
	}

	// get details of a project
	include = "" // trackers, issue_categories, enabled_modules
	// using projectId as integer
	pId, error := strconv.Atoi(projectId)
	if error == nil {
		project, error := c.GetProject(pId, include)
		if error == nil {
			fmt.Printf("%s\n", "=====get details of a project (using project Id)=====")
			fmt.Printf("project 1 - Name = %s\n", project.Name)
			fmt.Printf("project 1 - ID = %d\n", project.ID)
			fmt.Printf("project 1 - Status = %d\n", project.Status)

		} else {
			fmt.Printf("%s\n", error)
		}
	} else {
		fmt.Printf("%s\n", error)
	}

	// using projectId as string of project name
	project, error := c.GetProject(projectName, include)
	if error == nil {
		fmt.Printf("%s\n", "=====get details of a project (using project name)=====")
		fmt.Printf("project 1 - Name = %s\n", project.Name)
		fmt.Printf("project 1 - ID = %d\n", project.ID)
		fmt.Printf("project 1 - Status = %d\n", project.Status)

	} else {
		fmt.Printf("%s\n", error)
	}

	// create a new project
	projectNew := redmine4go.ProjectToSend{
		Name:                "Redmine project created by Go",
		Identifier:          "redmine4go",
		Description:         "a project generated by Redmine4Go",
		IsPublic:            false,
		ParentId:            nil,
		InheritMembers:      false,
		DefaultAssignedToId: nil,
		DefaultVersionId:    nil,
		TrackerIds:          nil,
		EnabledModuleNames:  nil,
		IssueCustomFieldIds: nil,
	}
	projectNewWrapper := redmine4go.ProjectToSendWrapper{Project: projectNew}
	projectNewReturn, error := c.CreateProject(projectNewWrapper)
	if error == nil {
		fmt.Printf("%s\n", "=====create a new project=====")
		fmt.Printf("project 1 - Name = %s\n", projectNewReturn.Name)
		fmt.Printf("project 1 - ID = %d\n", projectNewReturn.ID)
		fmt.Printf("project 1 - Status = %d\n", projectNewReturn.Status)
	} else {
		fmt.Printf("%s\n", error)
	}

	/*
		// archive a project
		// using projectId as integer
		error = c.ArchiveProject(projectId)
		if error == nil {
			fmt.Printf("%s\n", "=====archive a project (using project Id)=====")
			fmt.Printf("project %s is archived\n", projectId)
		} else {
			fmt.Printf("%s\n", error)
		}
		// using projectId as string of project name
		error = c.ArchiveProject(projectName)
		if error == nil {
			fmt.Printf("%s\n", "=====archive a project (using project name)=====")
			fmt.Printf("project %s is archived\n", projectName)
		} else {
			fmt.Printf("%s\n", error)
		}
	*/

	/*
		// unarchive a project
		// using projectId as integer
		error = c.UnarchiveProject(projectId)
		if error == nil {
			fmt.Printf("%s\n", "=====unarchive a project (using project Id)=====")
			fmt.Printf("project %s is unarchived\n", projectId)
		} else {
			fmt.Printf("%s\n", error)
		}
		// using projectId as string of project name
		error = c.UnarchiveProject(projectName)
		if error == nil {
			fmt.Printf("%s\n", "=====unarchive a project (using project name)=====")
			fmt.Printf("project %s is unarchived\n", projectName)
		} else {
			fmt.Printf("%s\n", error)
		}
	*/
}
